# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MAB2
version:      0.06
version_from: lib/Encode/MAB2.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.20
    Encode:                        1.41

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
